load:
  type: constant
  num_workers: 2
  worker_max_concurrency: 10
  stages:
  - rate: 20
    duration: 5
api:
  type: completion
server:
  type: vllm
  model_name: google/gemma-4-E4B-it
  ignore_eos: true
tokenizer:
  pretrained_model_name_or_path: Qwen/Qwen2.5-0.5B
data:
  type: shared_prefix
  shared_prefix:
    num_unique_system_prompts: 2
    num_users_per_system_prompt: 10
    system_prompt_len: 100
    question_len: 50
    output_len: 50
    enable_multi_turn_chat: true
metrics:
  type: prometheus
  prometheus:
    url: http://localhost:9090
    scrape_interval: 15
report:
  request_lifecycle:
    summary: true
    per_stage: true
    per_request: true
